workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Expo Prebuild
        script: |
          # توليد مجلد أندرويد من الصفر
          npx expo prebuild --platform android --non-interactive
      - name: Fix New Architecture
        script: |
          # إجبار تفعيل المعمارية الجديدة داخل المجلد المولّد
          sed -i '' 's/newArchEnabled=false/newArchEnabled=true/g' android/gradle.properties
          echo "newArchEnabled=true" >> android/gradle.properties
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug -PversionCode=$BUILD_NUMBER -PversionName=1.0.$BUILD_NUMBER
      - name: Export APK
        script: |
          cp android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/UofK_Chem.apk
    artifacts:
      - android/app/build/outputs/apk/debug/UofK_Chem.apk
      
