import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Lang = 'ar' | 'en';

const translations = {
  ar: {
    // Tabs
    academies: 'أكاديميات',
    news: 'الأخبار',
    schedule: 'الجدول',
    notes: 'الملاحظات',
    profile: 'الملف الشخصي',
    // Auth
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    studentId: 'الرقم الجامعي',
    noAccount: 'ليس لديك حساب؟ سجل الآن',
    haveAccount: 'لديك حساب؟ سجل دخول',
    appSubtitle: 'تطبيق طلاب الهندسة الكيميائية',
    registering: 'جاري التسجيل...',
    registerSuccess: 'تم التسجيل بنجاح',
    registerMsg: 'يمكنك الآن تسجيل الدخول والوصول إلى الملفات. الأخبار ستكون متاحة بعد موافقة المشرف.',
    ok: 'حسناً',
    error: 'خطأ',
    fillAll: 'الرجاء ملء جميع الحقول',
    // Subjects
    noSubjects: 'لا توجد أقسام بعد',
    editSubject: 'تعديل القسم',
    subjectName: 'اسم القسم',
    description: 'الوصف',
    save: 'حفظ',
    cancel: 'إلغاء',
    success: 'نجاح',
    subjectUpdated: 'تم تحديث القسم بنجاح',
    // Subject Details
    all: 'الكل',
    documents: 'مستندات',
    videos: 'فيديوهات',
    exercises: 'تمارين',
    noFiles: 'لا توجد ملفات بعد',
    noFilesCategory: 'لا توجد ملفات في هذا التصنيف',
    uploadFile: 'رفع ملف جديد',
    fileTitle: 'عنوان الملف',
    category: 'التصنيف',
    document: 'مستند/PDF',
    video: 'فيديو',
    exercise: 'تمرين',
    chooseFile: 'اختر ملف...',
    upload: 'رفع الملف',
    fileUploaded: 'تم رفع الملف بنجاح',
    deleteFile: 'حذف الملف',
    deleteConfirm: 'هل أنت متأكد من حذف هذا الملف؟',
    delete: 'حذف',
    downloaded: 'تم التحميل',
    fileSaved: 'تم حفظ الملف',
    // News
    noNews: 'لا توجد أخبار بعد',
    newPost: 'خبر جديد',
    postTitle: 'عنوان الخبر',
    postContent: 'محتوى الخبر',
    publish: 'نشر',
    postPublished: 'تم نشر الخبر بنجاح',
    poll: 'استطلاع',
    quiz: 'اختبار',
    text: 'نص',
    pollQuestion: 'سؤال الاستطلاع',
    option: 'الخيار',
    addOption: 'إضافة خيار',
    create: 'إنشاء',
    newPoll: 'استطلاع جديد',
    newQuiz: 'اختبار جديد',
    quizTitlePlaceholder: 'عنوان الاختبار',
    timerMin: 'مؤقت (دقائق)',
    autoPublish: 'نشر تلقائي',
    questionText: 'نص السؤال',
    addQuestion: 'إضافة سؤال',
    question: 'سؤال',
    startQuiz: 'ابدأ الاختبار',
    quizDone: 'تم الإجابة',
    submit: 'تسليم',
    submitted: 'تم التسليم',
    resultsLater: 'سيتم نشر النتائج لاحقاً',
    result: 'النتيجة',
    vote: 'صوت',
    votes: 'أصوات',
    like: 'إعجاب',
    reply: 'رد',
    replies: 'الردود',
    hide: 'إخفاء',
    comments: 'التعليقات',
    noComments: 'لا توجد تعليقات',
    addComment: 'أضف تعليق...',
    replyTo: 'رد على',
    // Profile
    editProfile: 'تعديل الملف الشخصي',
    approveStudents: 'الموافقة على الطلاب',
    addSubject: 'إضافة قسم جديد',
    logout: 'تسجيل الخروج',
    logoutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
    logoutBtn: 'خروج',
    supervisor: 'مشرف',
    student: 'طالب',
    approved: 'معتمد',
    pending: 'قيد الانتظار',
    joinRequests: 'طلبات الانضمام',
    noRequests: 'لا توجد طلبات معلقة',
    approve: 'موافقة',
    reject: 'رفض',
    newSubject: 'قسم جديد',
    tapToChange: 'اضغط لتغيير الصورة',
    bio: 'نبذة عنك',
    bioPlaceholder: 'اكتب نبذة عنك...',
    saveChanges: 'حفظ التغييرات',
    profileUpdated: 'تم تحديث الملف الشخصي',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'English',
    // Schedule
    noSchedule: 'لا توجد مواعيد بعد',
    addSchedule: 'إضافة موعد',
    day: 'اليوم',
    time: 'الوقت',
    location: 'المكان',
    subject: 'المادة',
    // Notes
    noNotes: 'لا توجد ملاحظات بعد',
    addNote: 'ملاحظة جديدة',
    noteTitle: 'عنوان الملاحظة',
    noteContent: 'محتوى الملاحظة',
    // Pending
    pendingTitle: 'في انتظار الموافقة',
    pendingMsg: 'حسابك قيد المراجعة من المشرف',
    // Offline
    offline: 'وضع عدم الاتصال',
    cachedData: 'بيانات محفوظة',
  },
  en: {
    academies: 'Academies',
    news: 'News',
    schedule: 'Schedule',
    notes: 'Notes',
    profile: 'Profile',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    studentId: 'Student ID',
    noAccount: "Don't have an account? Register now",
    haveAccount: 'Have an account? Login',
    appSubtitle: 'Chemical Engineering Students App',
    registering: 'Registering...',
    registerSuccess: 'Registration Successful',
    registerMsg: 'You can now login and access files. News will be available after admin approval.',
    ok: 'OK',
    error: 'Error',
    fillAll: 'Please fill all fields',
    noSubjects: 'No subjects yet',
    editSubject: 'Edit Subject',
    subjectName: 'Subject Name',
    description: 'Description',
    save: 'Save',
    cancel: 'Cancel',
    success: 'Success',
    subjectUpdated: 'Subject updated successfully',
    all: 'All',
    documents: 'Documents',
    videos: 'Videos',
    exercises: 'Exercises',
    noFiles: 'No files yet',
    noFilesCategory: 'No files in this category',
    uploadFile: 'Upload New File',
    fileTitle: 'File Title',
    category: 'Category',
    document: 'Document/PDF',
    video: 'Video',
    exercise: 'Exercise',
    chooseFile: 'Choose file...',
    upload: 'Upload File',
    fileUploaded: 'File uploaded successfully',
    deleteFile: 'Delete File',
    deleteConfirm: 'Are you sure you want to delete this file?',
    delete: 'Delete',
    downloaded: 'Downloaded',
    fileSaved: 'File saved',
    noNews: 'No news yet',
    newPost: 'New Post',
    postTitle: 'Post Title',
    postContent: 'Post Content',
    publish: 'Publish',
    postPublished: 'Post published successfully',
    poll: 'Poll',
    quiz: 'Quiz',
    text: 'Text',
    pollQuestion: 'Poll Question',
    option: 'Option',
    addOption: 'Add Option',
    create: 'Create',
    newPoll: 'New Poll',
    newQuiz: 'New Quiz',
    quizTitlePlaceholder: 'Quiz Title',
    timerMin: 'Timer (minutes)',
    autoPublish: 'Auto Publish',
    questionText: 'Question Text',
    addQuestion: 'Add Question',
    question: 'Question',
    startQuiz: 'Start Quiz',
    quizDone: 'Completed',
    submit: 'Submit',
    submitted: 'Submitted',
    resultsLater: 'Results will be published later',
    result: 'Result',
    vote: 'vote',
    votes: 'votes',
    like: 'Like',
    reply: 'Reply',
    replies: 'Replies',
    hide: 'Hide',
    comments: 'Comments',
    noComments: 'No comments',
    addComment: 'Add comment...',
    replyTo: 'Reply to',
    editProfile: 'Edit Profile',
    approveStudents: 'Approve Students',
    addSubject: 'Add New Subject',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    logoutBtn: 'Logout',
    supervisor: 'Supervisor',
    student: 'Student',
    approved: 'Approved',
    pending: 'Pending',
    joinRequests: 'Join Requests',
    noRequests: 'No pending requests',
    approve: 'Approve',
    reject: 'Reject',
    newSubject: 'New Subject',
    tapToChange: 'Tap to change photo',
    bio: 'About you',
    bioPlaceholder: 'Write about yourself...',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated',
    language: 'Language',
    arabic: 'العربية',
    english: 'English',
    noSchedule: 'No schedule yet',
    addSchedule: 'Add Schedule',
    day: 'Day',
    time: 'Time',
    location: 'Location',
    subject: 'Subject',
    noNotes: 'No notes yet',
    addNote: 'New Note',
    noteTitle: 'Note Title',
    noteContent: 'Note Content',
    pendingTitle: 'Pending Approval',
    pendingMsg: 'Your account is under review by admin',
    offline: 'Offline Mode',
    cachedData: 'Cached Data',
  },
};

interface LangContextType {
  lang: Lang;
  t: (key: string) => string;
  toggleLang: () => void;
  isRTL: boolean;
}

const LanguageContext = createContext<LangContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>('ar');

  useEffect(() => {
    AsyncStorage.getItem('app_lang').then(v => { if (v === 'en' || v === 'ar') setLang(v); });
  }, []);

  const toggleLang = () => {
    const newLang = lang === 'ar' ? 'en' : 'ar';
    setLang(newLang);
    AsyncStorage.setItem('app_lang', newLang);
  };

  const t = (key: string): string => {
    return (translations[lang] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
};
